#version 430 core

layout(local_size_x = 256) in;

layout(std430, binding = 1) buffer VelocityBuffer      { vec2 velocities[]; };
layout(std430, binding = 2) buffer AccelerationBuffer  { vec2 accelerations[]; };

uniform int particleCount;
uniform float dt;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= particleCount) return;

    velocities[i] += accelerations[i] * (0.5 * dt);
}
